alias cask="brew cask"
alias androidscreen="(adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g') | imgcat"
alias ls="$(brew --prefix)/opt/coreutils/libexec/gnubin/ls --color=auto -CFGhp"
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias code="/Applications/VSCodium.app/Contents/Resources/app/bin/codium"
alias bbfpr="brew bump-formula-pr --no-browse"
alias bbcpr="brew bump-cask-pr --no-browse"
alias line="lima nerdctl"
